In [5]:
import cv2
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import nibabel as nib
from starter_code.visualize import visualize
from starter_code.utils import load_case

import tensorflow as tf

In [6]:
volume, segmentation = load_case(123)
X = volume.get_data()
y = segmentation.get_data()

IMG_WIDTH = X.shape[2]
IMG_HEIGHT = X.shape[1]
IMG_SLICES = X.shape[0]
X = np.expand_dims(X, 3)

In [7]:
from neuralNetwork import *
model = makeModel(IMG_WIDTH, IMG_HEIGHT, 1)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [8]:
checkpointer = tf.keras.callbacks.ModelCheckpoint('model1.h5', verbose=1, save_best_only=True)

callbacks = [
    tf.keras.callbacks.EarlyStopping(patience=5, monitor='val_loss'),
    tf.keras.callbacks.TensorBoard(log_dir='logs')
]
results = model.fit(X, y, validation_split=0.1, batch_size=16, epochs=25, callbacks=callbacks, verbose=1)

Train on 350 samples, validate on 39 samples
Epoch 1/25
350/350 [==============================] - 23s 66ms/sample - loss: 0.0486 - accuracy: 0.9892 - val_loss: 0.0146 - val_accuracy: 1.0000
Epoch 2/25
350/350 [==============================] - 13s 37ms/sample - loss: 0.0158 - accuracy: 0.9958 - val_loss: 0.0176 - val_accuracy: 1.0000
Epoch 3/25
350/350 [==============================] - 13s 37ms/sample - loss: 0.0137 - accuracy: 0.9958 - val_loss: 0.0058 - val_accuracy: 1.0000
Epoch 4/25
350/350 [==============================] - 13s 37ms/sample - loss: 0.0086 - accuracy: 0.9959 - val_loss: 0.0015 - val_accuracy: 1.0000
Epoch 5/25
350/350 [==============================] - 13s 37ms/sample - loss: 0.0062 - accuracy: 0.9965 - val_loss: 0.0010 - val_accuracy: 1.0000
Epoch 6/25
350/350 [==============================] - 13s 37ms/sample - loss: 0.0048 - accuracy: 0.9971 - val_loss: 2.0801e-04 - val_accuracy: 1.0000
Epoch 7/25
350/350 [==============================] - 13s 37ms/sample - los

In [9]:
predicted = model.predict(X)

In [10]:
print(predicted)

[[[[1.79516992e-05]
   [1.88722615e-09]
   [1.42892764e-11]
   ...
   [3.54119078e-12]
   [2.42995152e-14]
   [1.62781873e-06]]

  [[1.28180784e-06]
   [1.62568842e-15]
   [2.04126752e-20]
   ...
   [1.33808485e-25]
   [7.17946980e-23]
   [7.76389647e-11]]

  [[1.06488605e-08]
   [7.20442260e-19]
   [7.30636502e-24]
   ...
   [1.75412333e-31]
   [1.42330710e-27]
   [9.02115152e-18]]

  ...

  [[6.01524386e-10]
   [1.35568422e-22]
   [9.75057963e-26]
   ...
   [8.86135488e-34]
   [7.18508586e-23]
   [1.87337532e-17]]

  [[1.25796959e-07]
   [7.20303605e-15]
   [1.09712465e-16]
   ...
   [3.67892631e-28]
   [2.70589522e-17]
   [1.72461681e-13]]

  [[5.56969053e-06]
   [9.96629862e-12]
   [9.85384625e-13]
   ...
   [2.61529798e-19]
   [5.50343815e-09]
   [1.42575132e-10]]]


 [[[1.79516828e-05]
   [1.88722260e-09]
   [1.42893024e-11]
   ...
   [3.54116411e-12]
   [2.42996083e-14]
   [1.62781396e-06]]

  [[1.28180898e-06]
   [1.62568842e-15]
   [2.04125977e-20]
   ...
   [1.33807980e-25]
 

In [17]:
%matplotlib qt
from visualizeSlider import *
cube_show_slider(cube=predicted[:,:,:,0], axis=0, cmap='gray')